import { timingSafeEqual } from "node:crypto";
import { createAdminClient } from "@/lib/csis/supabase/admin";
import { readInbound } from "@/lib/csis/inbound";
import { addCustomerMessage, createTicket } from "@/lib/csis/tickets";
import { supportEmail, TICKET_PREFIX } from "@/lib/csis/constants";

export const runtime = "nodejs";

const MAX_ATTACHMENT = 10 * 1024 * 1024;

function authorised(req: Request) {
  const expected = process.env.CSIS_INBOUND_SECRET;
  if (!expected) return false;
  const given =
    new URL(req.url).searchParams.get("secret") ?? req.headers.get("x-csis-secret") ?? "";
  const a = Buffer.from(given);
  const b = Buffer.from(expected);
  return a.length === b.length && timingSafeEqual(a, b);
}

/**
 * Inbound email webhook. Point your email provider's inbound route at
 *   https://<site>/api/inbound-email?secret=<CSIS_INBOUND_SECRET>
 * New mail opens a ticket; mail whose subject carries [CSIS-1234] (or that
 * replies to a known message) is added to that ticket.
 */
export async function POST(req: Request) {
  if (!authorised(req)) return new Response("Unauthorized", { status: 401 });

  const mail = await readInbound(req).catch(() => null);
  if (!mail) return new Response("Unreadable message", { status: 400 });

  // Never ticket our own mail or auto-replies — that is how mail loops start.
  if (mail.autoGenerated || mail.fromEmail === supportEmail().toLowerCase()) {
    return Response.json({ ignored: true });
  }

  const db = createAdminClient();

  if (mail.messageId) {
    const { data: dup } = await db
      .from("messages")
      .select("id")
      .eq("email_message_id", mail.messageId)
      .maybeSingle();
    if (dup) return Response.json({ duplicate: true });
  }

  // Find the ticket this belongs to: reference in the subject first, then headers.
  let ticket: { id: string; status: string; number: number } | null = null;
  const ref = mail.subject.match(new RegExp(`\\[${TICKET_PREFIX}-(\\d+)\\]`, "i"));
  if (ref) {
    const { data } = await db
      .from("tickets")
      .select("id, status, number, customers(email)")
      .eq("number", Number(ref[1]))
      .maybeSingle();
    const owner = (data?.customers as unknown as { email: string } | null)?.email;
    // Only accept the reference from the ticket's own customer.
    if (data && owner?.toLowerCase() === mail.fromEmail) ticket = data;
  }
  if (!ticket && mail.inReplyTo) {
    const { data } = await db
      .from("messages")
      .select("tickets(id, status, number, customers(email))")
      .eq("email_message_id", mail.inReplyTo)
      .maybeSingle();
    const t = data?.tickets as unknown as
      | { id: string; status: string; number: number; customers: { email: string } }
      | null;
    if (t && t.customers.email.toLowerCase() === mail.fromEmail) ticket = t;
  }

  let ticketId: string;
  let messageId: string;
  if (ticket) {
    ticketId = ticket.id;
    messageId = await addCustomerMessage(
      db,
      { id: ticket.id, status: ticket.status as never },
      mail.text,
      mail.messageId,
    );
  } else {
    const created = await createTicket(db, {
      email: mail.fromEmail,
      name: mail.fromName,
      subject: mail.subject.replace(/^((re|fwd?):\s*)+/i, ""),
      body: mail.text,
      source: "email",
      emailMessageId: mail.messageId,
    });
    ticketId = created.ticket.id;
    messageId = created.messageId;
  }

  for (const a of mail.attachments) {
    if (a.data.length > MAX_ATTACHMENT) continue;
    const path = `${ticketId}/${crypto.randomUUID()}-${a.filename.replace(/[^\w.\-]+/g, "_")}`;
    const { error } = await db.storage
      .from("csis-attachments")
      .upload(path, a.data, { contentType: a.contentType });
    if (!error) {
      await db.from("attachments").insert({
        message_id: messageId,
        ticket_id: ticketId,
        filename: a.filename,
        content_type: a.contentType,
        size: a.data.length,
        storage_path: path,
      });
    }
  }

  return Response.json({ ok: true, ticketId });
}
