/**
 * Normalises inbound-email webhooks into one shape. Supported:
 *  - Postmark inbound (JSON)            ← recommended
 *  - Mailgun / SendGrid routes (form)
 *  - A plain JSON body: { from, name?, subject, text, messageId?, inReplyTo? }
 */
export type InboundMail = {
  fromEmail: string;
  fromName: string;
  subject: string;
  text: string;
  messageId: string | null;
  inReplyTo: string | null;
  autoGenerated: boolean;
  attachments: { filename: string; contentType: string; data: Buffer }[];
};

const str = (v: unknown) => (typeof v === "string" ? v : "");

/** Parses `"Jane Doe" <jane@x.ie>` or a bare address. */
export function parseAddress(raw: string) {
  const m = raw.match(/^\s*"?([^"<]*?)"?\s*<([^>]+)>\s*$/);
  if (m) return { name: m[1].trim(), email: m[2].trim().toLowerCase() };
  return { name: "", email: raw.trim().toLowerCase() };
}

/** Drops the quoted history a mail client appends below the new reply. */
export function stripQuoted(text: string) {
  const lines = text.replace(/\r\n/g, "\n").split("\n");
  const cut = lines.findIndex(
    (l, i) =>
      /^On .+wrote:\s*$/i.test(l) ||
      (/^On .+/i.test(l) && /wrote:\s*$/i.test(lines[i + 1] ?? "")) ||
      /^-{2,}\s*Original Message\s*-{2,}/i.test(l) ||
      /^From:\s.+/.test(l) && /^Sent:/i.test(lines[i + 1] ?? ""),
  );
  const kept = (cut === -1 ? lines : lines.slice(0, cut)).filter(
    (l, i, arr) => !(l.startsWith(">") && arr.slice(i).every((x) => x.startsWith(">") || !x.trim())),
  );
  return kept.join("\n").trim();
}

const isAuto = (headers: Record<string, string>) => {
  const h = (k: string) => (headers[k.toLowerCase()] ?? "").toLowerCase();
  return (
    (h("auto-submitted") !== "" && h("auto-submitted") !== "no") ||
    h("x-autoreply") !== "" ||
    h("x-autorespond") !== "" ||
    ["bulk", "junk", "list"].includes(h("precedence"))
  );
};

const headerMap = (list: unknown) => {
  const out: Record<string, string> = {};
  if (Array.isArray(list)) {
    for (const h of list) out[str(h?.Name).toLowerCase()] = str(h?.Value);
  } else if (typeof list === "string") {
    for (const line of list.split(/\r?\n/)) {
      const i = line.indexOf(":");
      if (i > 0) out[line.slice(0, i).toLowerCase()] = line.slice(i + 1).trim();
    }
  }
  return out;
};

const clean = (id: string) => id.trim().replace(/^<|>$/g, "") || null;

export async function readInbound(req: Request): Promise<InboundMail | null> {
  const type = req.headers.get("content-type") ?? "";
  let f: Record<string, unknown> = {};
  const attachments: InboundMail["attachments"] = [];

  if (type.includes("application/json")) {
    f = await req.json();
    if (Array.isArray(f.Attachments)) {
      for (const a of f.Attachments as Record<string, unknown>[]) {
        if (str(a.Content)) {
          attachments.push({
            filename: str(a.Name) || "attachment",
            contentType: str(a.ContentType) || "application/octet-stream",
            data: Buffer.from(str(a.Content), "base64"),
          });
        }
      }
    }
  } else {
    const form = await req.formData();
    for (const [k, v] of form.entries()) {
      if (typeof v === "string") f[k] = v;
      else if (v.size > 0) {
        attachments.push({
          filename: v.name || "attachment",
          contentType: v.type || "application/octet-stream",
          data: Buffer.from(await v.arrayBuffer()),
        });
      }
    }
  }

  const headers = headerMap(f.Headers ?? f.headers ?? f["message-headers"]);
  const fromRaw = str(f.FromFull && (f.FromFull as { Email?: string }).Email)
    ? `${str((f.FromFull as { Name?: string }).Name)} <${str((f.FromFull as { Email?: string }).Email)}>`
    : str(f.From) || str(f.from) || str(f.sender);
  const from = parseAddress(fromRaw);
  if (!from.email.includes("@")) return null;

  const body =
    str(f.StrippedTextReply) ||
    stripQuoted(str(f.TextBody) || str(f.text) || str(f["body-plain"]) || "");
  const name = str(f.name) || from.name;

  return {
    fromEmail: from.email,
    fromName: name,
    subject: str(f.Subject) || str(f.subject) || "(no subject)",
    text: body || "(empty message)",
    messageId: clean(
      str(f.MessageID) || str(f.messageId) || str(f["Message-Id"]) || headers["message-id"] || "",
    ),
    inReplyTo: clean(str(f.inReplyTo) || str(f["In-Reply-To"]) || headers["in-reply-to"] || ""),
    autoGenerated: isAuto(headers),
    attachments,
  };
}
